### ISSUE TITLE
VPC Peering Clarification

### ISSUE THREAD

**Issue by hfern** [awsdocs/amazon-efs-user-guide#10]
The documentation [mentions](https://github.com/awsdocs/amazon-efs-user-guide/blob/master/doc_source/manage-fs-access-change-vpc.md)

> A *VPC peering connection* is a networking connection between two VPCs that enables you to route traffic between them using private Internet Protocol version 4 (IPv4) or Internet Protocol version 6 (IPv6) addresses. For more information on VPC peering, see What is VPC Peering? in the Amazon VPC Peering Guide.
>
>For Amazon EFS, you can work with VPC peering within a single AWS Region when using C5 or M5 instances. However, other VPC private connectivity mechanisms such as a VPN connection, interregion VPC peering, and intraregion VPC peering using other instance types are not supported.

There is no mention of how to actually get this setup working. An attempt at this ends with the DNS of the filesystem failing to resolve in the peered VPC.

The documentation should explain EFS VPC Peering better.

**Comment by awsdan** [comment]
Thanks for your feedback, we'll work to resolve the knowledge gap.

**Comment by rmarcuce** [comment]
Hi hfern, 

I've updated https://github.com/awsdocs/amazon-efs-user-guide/blob/master/doc_source/efs-different-vpc.md, a walkthrough showing how to mount an Amazon EFS file system that is in a different virtual private cloud (VPC). You do so using either an AWS transit gateway or an Amazon VPC peering connection.
