### ISSUE TITLE
File Sync API

### ISSUE THREAD

**Issue by josh-demuth** [awsdocs/amazon-efs-user-guide#19]
I'm not sure if this is the best place to ask this question but I can't seem to find information anywhere else. Is there a way to do something like [this](https://aws.amazon.com/answers/infrastructure-management/efs-backup/) but using File Sync? We need to automate the sync without using the console.

For example, I want to have a Lambda kick off and create a sync task (and ideally start the sync agent first so we don't have to run it running constantly). It seems there isn't a CLI or JS SDK method to accomplish this.

**Comment by rmarcuce** [comment]
Hi Josh, 

I'm the EFS technical writer, thanks for your feedback. Currently, EFS File Sync does not have an API that would allow you to programmatically automate a sync operation.

Rich

**Comment by davidmgre** [comment]
HI @josh-demuth - DataSync supports EFS-EFS tasks as of last year. 

https://aws.amazon.com/about-aws/whats-new/2019/05/aws-datasync-now-supports-efs-to-efs-transfer/
