### ISSUE TITLE
Pls document inode limit

### ISSUE THREAD

**Issue by anilgulecha** [awsdocs/amazon-efs-user-guide#35]
We're currently a GCP NFS user (filestore version). They call out increasing FS size to also increase inode count

https://cloud.google.com/filestore/docs/editing-instances

Can you pls call out the same for EFS. We're creating an AWS support ticket for now to get this info, but it would help for many usecases to have this explicitly documented (we run into this limit in our usecase - lots of tiny files).

**Comment by rmarcuce** [comment]
Thank you for your feedback. I'll work with the product managers and address your request for documenting the EFS inode limit.
