### ISSUE TITLE
Please include a section on how to use EFS cross-region

### ISSUE THREAD

**Issue by sachin-net** [awsdocs/amazon-efs-user-guide#36]
In the below [Documentation link](https://github.com/awsdocs/amazon-efs-user-guide/blob/master/doc_source/manage-fs-access-vpc-peering.md#mounting-from-another-account-in-the-same-vpc), please include an additional section on how to mount an efs from completely different region. 

This Issue is also related to one of the [closed Issue](https://github.com/aws/efs-utils/issues/33#issuecomment-522112455)
 where changing the region under "/etc/amazon/efs/efs-utils.conf" solved the issue. 

Joe from Amazon EFS team, did acknowledge that documentation may be unclear, but even after 1 year this section of this document is still confusing. I had to spent hours figure out that why it was not working. Hope this would be addressed at the earliest.

**Comment by rmarcuce** [comment]
I'll address your request in an upcoming documentation update.
