### ISSUE TITLE
Mixed units of metric and IEC

### ISSUE THREAD

**Issue by sponiro** [awsdocs/amazon-efs-user-guide#49]
On https://docs.aws.amazon.com/efs/latest/ug/performance.html units of IEC (1024^x) are used. But in several paragraphs the units used are the old style. For example:

> When burst credits are available, a file system can drive up to 100 MBps per terabyte (TB) of storage, with a minimum of 100 MBps. If no burst credits are available, a file system can drive up to 50 MBps per TB of storage with a minimum of 1 MBps.

Since this document makes use of mebibytes in other parts one could assume that above sentence refers to the metric version of MBps and not the legacy meaning with 1024^2 as a factor.

I suggest to consistently use the IEC units.

**Comment by rmarcuce** [comment]
Hi Robert, thanks for pointing out the inconsistency in units here. I am in the process of updating the guide to consistently use the IEC units. I'm closing your issue, with an update forthcoming.
