### ISSUE TITLE
EFS FQDN fails to resolve when storageClass is missing (undocumented scenario)

### ISSUE THREAD

**Issue by BloodyIron** [awsdocs/amazon-efs-user-guide#52]
For this section of documentation : https://github.com/awsdocs/amazon-efs-user-guide/blob/main/doc_source/troubleshooting-efs-mounting.md#file-system-mount-using-dns-name-fails

This can fail when you are using EFS encryption-in-transit and do NOT have the storageClass ( https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/encryption_in_transit/specs/storageclass.yaml ) in the cluster, and the error can seem nonsense. The error comes from the pod trying to use the PV/PVC, saying mount failed due to unable to resolve the FQDN and then mentions a seemingly irrelevant ARN for a role that doesn't have the permission for resolution, but isn't related to EFS or the EFS.CSI.Driver at all.

In my scenario, when I added this storageClass, the EFS interfacing immediately worked.

This is an undocumented solution so far as I can tell, and this troubleshooting documentation should add this along the lines of "If you're using EFS encryption-in-transit, check that your storageClass is correctly installed" and link to the correct one.

Honestly though, my confusion also was I wasn't sure if the storageClass was required, since the examples without EFS encryption-in-transit have blank storageClass declarations. IMO the storageClass being unclear as to whether you need or don't need it is what tripped me up here, and then a lack of documentation on this facet/scenario kept me stuck.

**Comment by rmarcuce** [comment]
Thanks for bringing this to our attention. I am working to use your input and provide a comprehensive response in the documentation to alert users and provide this guidance.

**Comment by rmarcuce** [comment]
@BloodyIron can you elaborate on how you made sure that the "storageClass was installed correctly"? This will help us understand your issue, and the details of your fix/workaround. Thank you.

**Comment by BloodyIron** [comment]
Okay so I want to reel back on my original report PARTLY.

I am not sure if the storageClass being missing was actually problematic, but I still think this aspect of the documentation should be validated and improved, since whether it is required is not clear between the encrypted/not scenarios (in-transit).

The EFS I had made was One-AZ when I needed Multi-AZ (but did not realise it). Rebuilding the EFS to be Multi-AZ and have Mount Targets to the AZs I now know I care about improved that.

As for how I installed the storageClass, well we do IaC/CD with Flux, so added the storageClass.yaml for this EFS SC to our repo, it was applied, and then things seemed to "work", but I think that may have been a combination of the storageClass being present _and_ the pod being on the right node that could actually reach the EFS.

So, I still recommend the storageClass aspect of the documentation be improved, as it still is confusing if you need it at all when you're not doing encryption-in-transit.

Sorry about the other mix-up though! Thanks for your time!

**Comment by rmarcuce** [comment]
Thank you!
