### ISSUE TITLE
RHEL6.9 version mismatch

### ISSUE THREAD

**Issue by apg036** [awsdocs/amazon-efs-user-guide#9]
The latest kernel version available is 2.6.32-696.30.1.el6.x86_64 (see https://access.redhat.com/articles/3078#RHEL6)
While the document mentions "kernel 2.6.32-704 or newer"

**Comment by awsdan** [comment]
Thanks for the issue. I'm working to get the proper supported versions, and I'll update the docs when I get them. Sorry for the inconvenience.

**Comment by awsdan** [comment]
I've updated the docs on docs.aws.amazon.com, and I'll be making a push to github later this week with other regularly scheduled doc updates. The correct info is:

RHEL 6.9 with kernel 2.6.32-696 or newer 

Thanks again for the issue!

**Comment by awsdan** [comment]
GitHub documentation has been updated.
